/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rc305' at '9/10/15 3:13 PM' with Gradle 2.5-rc-2
 *
 * @author rc305, @date 9/10/15 3:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
